"""create drone_record and pipeline_run tables

Revision ID: 5646680faa2f
Revises: 
Create Date: 2026-07-19 11:00:35.267251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5646680faa2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.String(length=64), nullable=False),
    sa.Column('drone_type', sa.String(length=64), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('battery_percent', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LANDED', 'LOST_SIGNAL', name='drone_status'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drone_id', 'timestamp', 'source', name='uq_drone_record_identity')
    )
    with op.batch_alter_table('drone_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drone_record_drone_id'), ['drone_id'], unique=False)
        batch_op.create_index('ix_drone_record_lat_lng', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_drone_record_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drone_record_timestamp'), ['timestamp'], unique=False)

    op.create_table('pipeline_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'COMPLETED', 'FAILED', name='pipeline_run_status'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('valid_records', sa.Integer(), nullable=False),
    sa.Column('invalid_records', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_run')
    with op.batch_alter_table('drone_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drone_record_timestamp'))
        batch_op.drop_index(batch_op.f('ix_drone_record_operator_id'))
        batch_op.drop_index('ix_drone_record_lat_lng')
        batch_op.drop_index(batch_op.f('ix_drone_record_drone_id'))

    op.drop_table('drone_record')
    # ### end Alembic commands ###
